### ISSUE TITLE
MQTT Frage

### ISSUE THREAD

**Issue by Nighthawk2008** [ESPWortuhr/Multilayout-ESP-Wordclock#222]
Gibt es eine Doku für die Befehle Par Mqtt?

vielen dank.

PS. Super Arbeit!!

**Comment by udo1toni** [comment]
Meines Wissens funktioniert mqtt bisher leider noch nicht.

**Comment by pfefferle** [comment]
MQTT support wäre großartig! Ich hab die Uhr im Flur stehen und würde gerne, abhängig vom Status von Sensoren in Home Assistant (z.B. "fenster offen", "wasser im keller", ...) die Farbe der Uhr anpassen um zu sehen ob alles in ordnung ist, wenn ich das Haus verlasse oder nach hause komme ;)

Übrigens: Vielen Dank für das großartige Projekt, es läuft wunderbar und hat ein paar schönes Gimmicks :)

**Comment by thuetti1** [comment]
Über mqtt Support würde ich mich auch freuen. Habe in Homeassistant das Mosquitto addon laufen bekomme aber keine Verbindung zustande. 

Vielen Dank für die Mühen

**Comment by dbambus** [comment]
Hallo an Alle ;-),

ich werde mich der Sache mal annehmen und schauen wo der Wurm drin ist ;-) 

Bin aber grad noch im Urlaub ohne Laptop mit Sonnenschein und 20°C 

Mit freundlichen Grüßen
David

**Comment by pfefferle** [comment]
@dbambus Ich hab gerade ein paar tests gemacht und ich schaffe es zumindest mal die Farbe über MQTT zu ändern... das scheint also zu funktionieren... effekte klappen noch nicht, aber das kann auch an mir liegen ;)

**Comment by pfefferle** [comment]
Home Assistant integration funktioniert auch teilweise:

```YAML
light:
  - name: Wortuhr
    unique_id: "wortuhr"
    schema: template
    effect_list:
      - Wortuhr
      - Sekundenanzeige
      - Laufschrift
      - Regenbogen
      - Farbwechsel
      - Farbe
    command_topic: "wortuhr" #topic name
    state_topic: "wortuhr" #topic name
    command_on_template: >
      {"state": "ON"
      {%- if red is defined and green is defined and blue is defined -%}
      , "color": [{{ red }}, {{ green }}, {{ blue }}]
      {%- endif -%}
      {%- if effect is defined -%}
      , "effect": "{{ effect }}"
      {%- endif -%}
      }
    command_off_template: '{"state": "off"}'
    state_template: "{{ value_json.state }}"
    red_template: "{{ value_json.color[0] }}"
    green_template: "{{ value_json.color[1] }}"
    blue_template: "{{ value_json.color[2] }}"
    effect_template: "{{ value_json.effect }}"
```

Ein Problem ist, dass Home Assistant mit "on"/"off" arbeitet, im code aber explizit auf "ON" geprüft wird, dadurch kommt Home Assistant mit dem Status durcheinander. Die Uhr scheint außerdem abzuschmieren, wenn man nur eine Teilmenge schickt. Also wenn man die Farbe ändert, wird der `effect` nicht mit geschickt.
